### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by yokinanya** [Sennagi-fox/MG-Aide#1]
- 代码别传到release上面（工程文件fep可以解压），代码仓库是给你放代码的
- 仓库别用包名命名，尽量用软件英文名字，比如MG-Aide
- release是用于版本发布的，与软件本身无关的不建议放这里
- 关于 Git 的学习，可以看看[这个](https://www.liaoxuefeng.com/wiki/896043488029600)

**Comment by Sennagi-fox** [comment]
行吧
